spring.application.name=platform
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoint.health.group.db.include=mongo
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true
upstox.api.url=${UPSTOX_API_URL}
upstox.api.access-token=${UPSTOX_API_TOKEN}